FROM scimma/base:0.1.1
RUN yum -y update && yum -y install git unzip
RUN cd /usr/local/src && \
    curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -rf aws
ADD . /root/stream2hop
RUN pip3 install -e /root/stream2hop
WORKDIR /tmp
ENTRYPOINT ["python3" , "/root/stream2hop/scripts/tns_run.py"]