#!/usr/bin/python3
import gcn.voeventclient
import multiprocessing
import xmltodict
import Utils
import json

    
host=("209.208.78.170", "45.58.43.186", "50.116.49.68", "68.169.57.253")
port=8099
gcn.voeventclient.listen(host=host, port=port, handler=Utils.writeToScimma)
