name: BuildTest
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-18.04
    name:    build
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: installtest
        run:  chmod ugo+rx scripts/*.sh && scripts/mitest.sh
